// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buwtzuktuyutnvxvswwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1d3R6dWt0dXl1dG52eHZzd3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDk1NTAsImV4cCI6MjA3MjcyNTU1MH0.pih7AN2aPKUqbaUquCIpzztJ6qfCrQJLtsE1WQlgSB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});